spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: doctor
  profiles:
    active: ${PROFILE:dev}
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: ${PORT:0}
  forward-headers-strategy: framework
logging:
  level:
    root: info
    org.springframework.web: info
    br.com.jtech.services.doctor: debug
  file:
    name: ./logs/${spring.application.name}.log
springdoc:
  api-docs:
    groups:
      enabled: 'true'
    path: /doc/doctor/v3/api-documents
  swagger-ui:
    enabled: 'true'
    path: /doc/doctor/v1/api.html

eureka:
  client:
    service-url:
      defaultZone:
        http://${EUREKA_USER:root}:${EUREKA_PASS:root}@${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka
